# AssQ 6-Apr SVM-1 

In [ ]:
Q1. What is the mathematical formula for a linear SVM?

In [ ]:
So now we can say that our that are SVM Error = Margin Error + Classification Error.
The higher the margin, the lower would-be margin error, and vice versa.

x+b=0 where w is a vector normal to hyperplane and b is an offset. If the value of w. x+b>0 then 
we can say it is a positive point otherwise it is a negative point.
Now we need (w,b) such that the margin has a maximum distance.

Linear SVM: Linear SVM is used for linearly separable data, which means if a dataset can be classified
into two classes by using a single straight line, then such data is termed as linearly separable data, 
and classifier is used called as Linear SVM classifier.

In [ ]:
Q2. What is the objective function of a linear SVM?

In [ ]:
The objective of the support vector machine algorithm is to find a hyperplane in an N-dimensional space
(N — the number of features) that distinctly classifies the data points.
To separate the two classes of data points, there are many possible hyperplanes that could be chosen.

The objective of a linear regression model is to find a relationship between one or more features(independent variables) and
a continuous target variable(dependent variable).

In ε-SVM regression, the set of training data includes predictor variables and observed response values. 
The goal is to find a function f(x) that deviates from yn by a value no greater than ε for each training point x,
and at the same time is as flat as possible.

SVM works by mapping data to a high-dimensional feature space so that data points can be categorized, 
even when the data are not otherwise linearly separable. A separator between the categories is found, 
then the data are transformed in such a way that the separator could be drawn as a hyperplane.

In [ ]:
Q3. What is the kernel trick in SVM?

In [ ]:
The “trick” is that kernel methods represent the data only through a set of pairwise similarity comparisons
between the original data observations x (with the original coordinates in the lower dimensional space),
instead of explicitly applying the transformations ϕ(x) and representing the data by these transformed.

The kernel trick allows us to project data from a training set 
which isn't linearly separable into a higher dimensional space where it becomes linearly separable.

The kernel trick involves using such functions to treat inner-products between observations in the spaces described by the kernel function.

The ultimate benefit of the kernel trick is that the objective function we are optimizing to fit the higher 
dimensional decision boundary only includes the dot product of the transformed feature vectors. Therefore,
we can just substitute these dot product terms with the kernel function, and we don't even use ϕ(x).

In [ ]:
Q4. What is the role of support vectors in SVM Explain with example 

In [ ]:
Support vectors are data points that are closer to the hyperplane and influence 
the position and orientation of the hyperplane.
Using these support vectors, we maximize the margin of the classifier. 
Deleting the support vectors will change the position of the hyperplane.
These are the points that help us build our SVM.

According to the SVM algorithm we find the points closest to the line from both the classes. 
These points are called support vectors.
Now, we compute the distance between the line and the support vectors.
This distance is called the margin.

Support vector machines (SVMs) are a set of supervised learning methods used for classification,
regression and outliers detection. The advantages of support vector machines are: Effective in high dimensional spaces. 
Still effective in cases where number of dimensions is greater than the number of samples.

In [ ]:
Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in SVM?

In [ ]:
Hyperplane ---------
It is a decision boundary that differentiates the two classes in SVM.
A data point falling on either side of the hyperplane can be attributed to different classes.
The dimension of the hyperplane depends on the number of input features in the dataset.

We all know the equation of a hyperplane is w.x+b=0 where w is a vector normal to hyperplane and b is an offset. 
If the value of w.x+b>0 then we can say it is a positive point otherwise it is a negative point.


Margin: it is the distance between the hyperplane and the observations closest to the hyperplane (support vectors).
In SVM large margin is considered a good margin. There are two types of margins hard margin and soft margin.

The margin is calculated as the perpendicular distance from the line to only the closest points.
Only these points are relevant in defining the line and in the construction of the classifier.
These points are called the support vectors.


Soft margin----------
Soft margin SVM allows some misclassification to happen by relaxing the hard constraints of Support Vector Machine.
Soft margin SVM is implemented with the help of the Regularization parameter (C).
Regularization parameter (C): It tells us how much misclassification we want to avoid.


Hard margin-----------
Hard-Margin SVMs. Hard-Margin SVMs address the generalization problem of perceptrons by maximizing the mar- gin, 
formally defined as the minimum distance from the decision boundary to the training points.


The difference between a hard margin and a soft margin in SVMs lies in the separability of the data. 
If our data is linearly separable, we go for a hard margin. However,
if this is not the case, it won't be feasible to do that.

In [ ]:
Q6. SVM Implementation through Iris dataset.
~ Load the iris dataset from the scikit-learn library and split it into a training set and a testing setl
~ Train a linear SVM classifier on the training set and predict the labels for the testing setl
~ Compute the accuracy of the model on the testing setl
~ Plot the decision boundaries of the trained model using two of the featuresl
~ Try different values of the regularisation parameter C and see how it affects the performance of 
the model.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset=load_iris()

In [5]:
import seaborn as sns

In [6]:
df=sns.load_dataset('iris')

In [7]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
#Independent and dependent features
X=df.iloc[:,:-1]
y=dataset.target

In [10]:
X,y

(     sepal_length  sepal_width  petal_length  petal_width
 0             5.1          3.5           1.4          0.2
 1             4.9          3.0           1.4          0.2
 2             4.7          3.2           1.3          0.2
 3             4.6          3.1           1.5          0.2
 4             5.0          3.6           1.4          0.2
 ..            ...          ...           ...          ...
 145           6.7          3.0           5.2          2.3
 146           6.3          2.5           5.0          1.9
 147           6.5          3.0           5.2          2.0
 148           6.2          3.4           5.4          2.3
 149           5.9          3.0           5.1          1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [13]:
from sklearn.svm import SVR

In [14]:
svr=SVR(kernel='linear')

In [15]:
svr.fit(X_train,y_train)

SVR(kernel='linear')

In [16]:
svr.coef_

array([[-0.19118067,  0.01995179,  0.34374913,  0.4410079 ]])

In [17]:
## Prediction
y_pred=svr.predict(X_test)

In [18]:
y_pred

array([ 1.18010596e+00,  1.74294757e+00, -1.01880092e-01,  1.34515897e+00,
       -6.77634530e-02,  9.80978711e-01,  1.44417246e+00,  1.04824991e+00,
       -5.05114278e-02,  1.33916517e+00,  1.45047518e+00,  1.78890615e+00,
        1.19555085e+00, -5.46309237e-02,  1.57007932e-03,  1.82941224e+00,
        1.42608442e+00,  6.58450045e-03,  4.36756895e-02, -1.38508459e-01,
        1.90955769e+00,  1.98036985e+00,  1.56720353e+00,  1.44342428e-01,
        1.28999624e+00, -4.67793432e-02,  1.19593000e+00,  1.29493525e+00,
        1.27609196e+00,  2.12991082e+00,  1.20347266e+00,  1.17682019e+00,
        1.63556076e+00,  2.01140527e+00,  1.65495054e+00,  6.71363756e-03,
        1.92326567e+00,  1.97123594e+00])

In [19]:
from sklearn.metrics import r2_score

In [20]:
print(r2_score(y_test,y_pred))

0.916269719220456


# Hyperparametere Tuning With SVR

In [21]:
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':['linear'],
              'epsilon':[0.1,0.2,0.3]
              }

In [22]:
grid=GridSearchCV(SVR(),param_grid=param_grid,refit=True,cv=5,verbose=3)

In [23]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 75 candidates, totalling 375 fits
[CV 1/5] END C=0.1, epsilon=0.1, gamma=1, kernel=linear;, score=0.871 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=1, kernel=linear;, score=0.922 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=1, kernel=linear;, score=0.941 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=1, kernel=linear;, score=0.895 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=1, kernel=linear;, score=0.956 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.871 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.922 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.941 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.895 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.956 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'epsilon': [0.1, 0.2, 0.3],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [24]:
grid.best_params_

{'C': 1, 'epsilon': 0.2, 'gamma': 1, 'kernel': 'linear'}

In [25]:
## Prediction
y_pred4=grid.predict(X_test)
print(r2_score(y_test,y_pred4))


0.9215588925566922
